spring.application.name=youmr_springboot

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.datasource.url=jdbc:mysql://localhost:3306/youmr?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=admin
spring.datasource.password=admin_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA ??
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.fo rmat_sql=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false